In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
spam_df=pd.read_csv('combined_data.csv')

In [3]:
spam_df

label                                               text
0          1  ounce feather bowl hummingbird opec moment ala...
1          1  wulvob get your medircations online qnb ikud v...
2          0   computer connection from cnn com wednesday es...
3          1  university degree obtain a prosperous future m...
4          0  thanks for all your answers guys i know i shou...
...      ...                                                ...
83443      0  hi given a date how do i get the last date of ...
83444      1  now you can order software on cd or download i...
83445      1  dear valued member canadianpharmacy provides a...
83446      0  subscribe change profile contact us long term ...
83447      1  get the most out of life ! viagra has helped m...

[83448 rows x 2 columns]

In [4]:
spam_df.head(10)

label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...
5      0  larry king live at escapenumber escapenumber p...
6      0  michael pobega wrote i'm not sure if it's the ...
7      0  hi i have this error tr sample escapenumber es...
8      1  works gateway world art explore tattooing full...
9      1  upon this account he is not only very cautious...

In [5]:
spam_df.tail(10)

label                                               text
83438      1  downloadable software ds is a fast paced compa...
83439      1  http printlost hk viagra escapenumber pills x ...
83440      0  howstuffworks r lifestyle april escapenumber e...
83441      1  lowest prices hbie qsxh gycj swlw swsszguohc z...
83442      0  tewk wrote patch was to large to attach so htt...
83443      0  hi given a date how do i get the last date of ...
83444      1  now you can order software on cd or download i...
83445      1  dear valued member canadianpharmacy provides a...
83446      0  subscribe change profile contact us long term ...
83447      1  get the most out of life ! viagra has helped m...

In [6]:
spam_df.describe()

label
count  83448.000000
mean       0.526196
std        0.499316
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000

In [7]:
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83448 entries, 0 to 83447
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   83448 non-null  int64 
 1   text    83448 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.3+ MB


In [11]:
spam_df['label'].value_counts()

label
1    43910
0    39538
Name: count, dtype: int64

## Visualize the Data


In [12]:
ham=spam_df[spam_df['label']==0]

In [13]:
spam=spam_df[spam_df['label']==1]

In [14]:
ham

label                                               text
2          0   computer connection from cnn com wednesday es...
4          0  thanks for all your answers guys i know i shou...
5          0  larry king live at escapenumber escapenumber p...
6          0  michael pobega wrote i'm not sure if it's the ...
7          0  hi i have this error tr sample escapenumber es...
...      ...                                                ...
83436      0  hi list please see the following simple exampl...
83440      0  howstuffworks r lifestyle april escapenumber e...
83442      0  tewk wrote patch was to large to attach so htt...
83443      0  hi given a date how do i get the last date of ...
83446      0  subscribe change profile contact us long term ...

[39538 rows x 2 columns]

In [15]:
spam

label                                               text
0          1  ounce feather bowl hummingbird opec moment ala...
1          1  wulvob get your medircations online qnb ikud v...
3          1  university degree obtain a prosperous future m...
8          1  works gateway world art explore tattooing full...
9          1  upon this account he is not only very cautious...
...      ...                                                ...
83439      1  http printlost hk viagra escapenumber pills x ...
83441      1  lowest prices hbie qsxh gycj swlw swsszguohc z...
83444      1  now you can order software on cd or download i...
83445      1  dear valued member canadianpharmacy provides a...
83447      1  get the most out of life ! viagra has helped m...

[43910 rows x 2 columns]

In [16]:
print('Spam Percentage =',(len(spam)/len(spam_df))*100,'%')

Spam Percentage = 52.619595436679134 %


In [17]:
print('Ham Percentage =',(len(ham)/len(spam_df))*100,'%')

Ham Percentage = 47.38040456332087 %


## Applying CountVectorizer to our Spam Ham Example

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
spamham_countVectorizer=vectorizer.fit_transform(spam_df['text'])

In [21]:
print(vectorizer.get_feature_names_out())

['00' '000' '0000' ... '小楊' '拒信pt' '李俊杰']


In [22]:
spamham_countVectorizer.shape

(83448, 310813)

## Dividing the Cell for Training and Testing Prior to Training

In [25]:
label=spam_df['label']
X=spamham_countVectorizer
y=label

In [26]:
X.shape

(83448, 310813)

In [27]:
y.shape

(83448,)

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33)

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
NB_classifier=MultinomialNB()
NB_classifier.fit(X_train,y_train)

MultinomialNB()

## Evaluating The Model 

In [31]:
from sklearn.metrics import classification_report,confusion_matrix

In [32]:
y_predict_train=NB_classifier.predict(X_train)
y_predict_train

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [33]:
cm=confusion_matrix(y_train,y_predict_train)

In [34]:
print(cm)

[[26163   318]
 [  638 28791]]


In [35]:
y_predict_test=NB_classifier.predict(X_test)
y_predict_test

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
cm=confusion_matrix(y_test,y_predict_test)
print(cm)

[[12846   211]
 [  504 13977]]


In [37]:
print(classification_report(y_test,y_predict_test))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97     13057
           1       0.99      0.97      0.98     14481

    accuracy                           0.97     27538
   macro avg       0.97      0.97      0.97     27538
weighted avg       0.97      0.97      0.97     27538



In [40]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.naive_bayes import MultinomialNB


# Set up k-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform k-fold cross-validation
scores = cross_val_score(NB_classifier, X_train, y_train, cv=kf)

# Print the cross-validation scores
print("------ Naive Baiyes ------")
print("Cross-validation scores: ", scores)
print("Mean cross-validation score: ", np.mean(scores))


------ Naive Baiyes ------
Cross-validation scores:  [0.97585405 0.97495976 0.97764264 0.97281345 0.97352889 0.97621177
 0.97621177 0.97746378 0.97817922 0.97817922]
Mean cross-validation score:  0.9761044535861206


In [60]:
y_predict_test=NB_classifier.predict(X_test)
y_predict_test

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [39]:
print(classification_report(y_test,y_predict_test))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97     13057
           1       0.99      0.97      0.98     14481

    accuracy                           0.97     27538
   macro avg       0.97      0.97      0.97     27538
weighted avg       0.97      0.97      0.97     27538



## Model 2: Logistic Regression

In [41]:
from sklearn.linear_model import LogisticRegression

In [52]:
model_logreg = LogisticRegression(penalty="l2", C=1)

In [54]:
model_logreg.fit(X_train, y_train)

LogisticRegression(C=1, max_iter=10000)

In [55]:
y_predict_train=model_logreg.predict(X_train)
y_predict_train

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [56]:
cm=confusion_matrix(y_train,y_predict_train)
print(cm)

[[26403    78]
 [    7 29422]]


In [57]:
y_predict_test=model_logreg.predict(X_test)
y_predict_test

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [58]:
cm=confusion_matrix(y_test,y_predict_test)
print(cm)

[[12795   262]
 [  158 14323]]


In [59]:
print(classification_report(y_test,y_predict_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98     13057
           1       0.98      0.99      0.99     14481

    accuracy                           0.98     27538
   macro avg       0.98      0.98      0.98     27538
weighted avg       0.98      0.98      0.98     27538



In [60]:
from sklearn.model_selection import cross_val_score, KFold


# Set up k-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform k-fold cross-validation
scores = cross_val_score(model_logreg, X_train, y_train, cv=kf)

# Print the cross-validation scores
print("Cross-validation scores: ", scores)
print("Mean cross-validation score: ", np.mean(scores))


KeyboardInterrupt: 

In [61]:
spam_df['text'].duplicated().sum()

2

## Model 3: SVC

In [ ]:
from sklearn.svm import SVC
model_svc = SVC()


In [ ]:
model_svc.fit(X_train, y_train)


In [ ]:
y_predict_train=model_svc.predict(X_train)
y_predict_train
cm=confusion_matrix(y_train,y_predict_train)
print(cm)

In [ ]:
y_predict_test=model_svc.predict(X_test)
y_predict_test
cm=confusion_matrix(y_test,y_predict_test)
print(cm)

In [ ]:
print(classification_report(y_test,y_predict_test))

In [ ]:
from sklearn.model_selection import cross_val_score, KFold


# Set up k-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform k-fold cross-validation
scores = cross_val_score(model_svc, X_train, y_train, cv=kf)

# Print the cross-validation scores
print("Cross-validation scores: ", scores)
print("Mean cross-validation score: ", np.mean(scores))